- lib/reverse_markdown/converters/pre.rb
- spec/lib/reverse_markdown/converters/pre_spec.rb
Hello everyone,
This is my take on support for syntax highlighting. There have been #41 and #43 targeting the same topic already, but let me share some thoughts about that with you and have a quick discussion.
**Specs** Please add specs. Without specs (and examples) I can't find out if the pull requests are working or doing what they are supposed to.
**Which highlighter to support?** Like @schkovich pointed out, there are a lot of syntax highlighters out there. Supporting all of them inside the main gem would be too much. In this PR I only support the github way of highlighting, which fits the current policy within ReverseMarkdown - support plain and github flavored markdown only.
**Use existing tools** I like the idea of a plugin system for syntax highlighters, but while I was writing …
> Support syntax highlighting for pre tags

- lib/reverse_markdown/converters.rb
This makes it possible to pass through a tag that has a defined converter by unregistering that tag's converter before calling convert. I had a requirement to always pass through `div` and `table` tags.
```ruby
ReverseMarkdown::Converters.unregister(:div)
ReverseMarkdown::Converters.unregister(:table)
markdown = ReverseMarkdown.convert(html)
```
Thanks for the great gem!
> Add the ability to unregister a converter

- lib/reverse_markdown/cleaner.rb
- spec/lib/reverse_markdown/cleaner_spec.rb
The cleaner would duplicate lines than only contained whitespace because the entire string was considered both the beginning and the end of the string.
```
foo \nbar \n \n  \nfoo
```
was "cleaned" to be
```
foo \nbar \n \n \n  \n  \nfoo
```
This fixes that.
> Don't try to clean lines that only contain whitespace

- lib/reverse_markdown/converters/em.rb
- lib/reverse_markdown/converters/strong.rb
- spec/assets/basic.html
- spec/components/basic_spec.rb
- spec/components/from_the_wild_spec.rb
Code like `<em> em with leading and trailing </em>whitespace` failed to convert properly.
The "from the wild" test didn't have the correct expected output. It actually had the same whitespace issue that I fixed.
> Handle leading/trailing whitespace in em and strong

- lib/reverse_markdown/converters/text.rb
- spec/lib/reverse_markdown/converters/text_spec.rb
Related to https://github.com/xijo/reverse_markdown/issues/46.
Converting a `p` tag which includes code with underscores or asterisks within backticks results in escaped characters:
```
ReverseMarkdown.convert("<p>`foo_bar 2**3`</p>")
=> "`foo\\_bar 2\\*\\*3`\n\n"
```
This PR makes sure to preserve these characters when within backticks.
Thanks for the gem :)
/cc @xijo
> Preserve underscores + asterisks inside code spans

- lib/reverse_markdown/converters/li.rb
- spec/assets/lists.html
- spec/components/lists_spec.rb
Problem: given a nested list between adjacent list items like this:
````
<ul>
<li>alpha</li>
<li>bravo
<ul>
<li>bravo alpha</li>
<li>bravo bravo
</ul>
</li>
<li>charlie</li>
</ul>
````
Reverse markdown produces an extra newline:
````
- alpha
- bravo
- bravo alpha
- bravo bravo
- charlie
````
This PR fixes the `li` converter and removes the extra newline to produce this markdown:
````
- alpha
- bravo
- bravo alpha
- bravo bravo
- charlie
````
Specs included.
> Nested indentation fix for nested list items with adjacent parent list items

- lib/reverse_markdown/converters/a.rb
- lib/reverse_markdown/converters/base.rb
- lib/reverse_markdown/converters/blockquote.rb
- lib/reverse_markdown/converters/br.rb
- lib/reverse_markdown/converters/bypass.rb
- lib/reverse_markdown/converters/code.rb
- lib/reverse_markdown/converters/del.rb
- lib/reverse_markdown/converters/div.rb
- lib/reverse_markdown/converters/drop.rb
- lib/reverse_markdown/converters/em.rb
- lib/reverse_markdown/converters/h.rb
- lib/reverse_markdown/converters/hr.rb
- lib/reverse_markdown/converters/ignore.rb
- lib/reverse_markdown/converters/img.rb
- lib/reverse_markdown/converters/li.rb
- lib/reverse_markdown/converters/ol.rb
- lib/reverse_markdown/converters/p.rb
- lib/reverse_markdown/converters/pass_through.rb
- lib/reverse_markdown/converters/pre.rb
- lib/reverse_markdown/converters/strong.rb
- lib/reverse_markdown/converters/table.rb
- lib/reverse_markdown/converters/td.rb
- lib/reverse_markdown/converters/tr.rb
- spec/lib/reverse_markdown/converters/strong_spec.rb
We are traversing the document top-down, so we shouldn't ever need to traverse back up.  In very large documents, traversing back up can be expensive.  This will pass around a state that can be used to track parent information rather than ascending back up the tree.
:warning: 
This is something I would consider worthy of a major version bump, as it changes the API a little bit. Anyone with currently built custom converters will encounter errors until they modify them to accept the `state` argument and then pass that argument to `treat_children`
Some performance numbers for parsing [this document](https://gist.github.com/craig-day/ba25eab699b164db04d2)
**before**
```
unknown tag mode :pass_through
time: 0.535165
unknown tag mode :drop
time: 0.577383
unknown tag mode :bypass
time: 0.539775 …
```
> Avoid traversing back up the tree

- README.md
- lib/reverse_markdown/cleaner.rb
- lib/reverse_markdown/config.rb
- spec/assets/basic.html
- spec/components/basic_spec.rb
- spec/lib/reverse_markdown/cleaner_spec.rb
Based on our conversation here a while back, I wrote the following code:
https://github.com/xijo/reverse_markdown/commit/236a9afe4dc1b755914a712ca7e8c8e89d9b6ce0#commitcomment-11240524
This pull request adds a config option: `Default border`. Which set to a single whitespace as default. It will add extra border characters where the source does not have it. 
If we pass default border to be empty, this request allows resulting markdown to stay true to the source html.
> allow default_border to be empty using config option

- lib/reverse_markdown/converters/text.rb
- spec/lib/reverse_markdown/converters/text_spec.rb
At this time, the Markdown:
<p>&lt;foo&gt;</p>
…reverses into:
<foo>
…which re-renders into HTML as:
<p><foo></p>
This changeset changes the resulting Markdown to:
\<foo\>
> Fix text escaping

- lib/reverse_markdown/converters/base.rb
- lib/reverse_markdown/converters/text.rb
- spec/assets/from_the_wild.html
- spec/components/from_the_wild_spec.rb
Little bit of a weird, but possible scenario.  Right now, we will escape `*` and `_` no matter what. Well, what if they have already been escaped? This modifies the `escape_keychars` function a little bit to make sure that we don't end up with something like `foo\\\\\\\\\\\_bar` when all we want is `foo\_bar`.
> make sure we don't over escape * or _

- lib/reverse_markdown/converters/a.rb
- spec/assets/anchors.html
- spec/components/anchors_spec.rb
As already described in issue #56, given:
```html
(<a href="http://foobar.com">link</a>)
```
I would expect to see:
```markdown
([link](http://foobar.com))
```
But the actual result has an extra space after the left parenthesis:
```markdown
( [link](http://foobar.com))
```
The implementation also handles the case when there is an exclamation mark before the link (by adding a space).
> Remove extra space before links

- lib/reverse_markdown/converters/pre.rb
- spec/lib/reverse_markdown/converters/pre_spec.rb
- spec/spec_helper.rb
While using this gem, we had an issue where new lines within `pre` code blocks were not being preserved. On inspection, I found that we were recording new lines as `br` tags within the `pre` block, and the existing converter was dropping them with the line `node.text.strip.lines.to_a.join("    ")`.
Since it's permitted to have phrasing content as the children of `pre` nodes, I decided to look for a solution here, using the `treat_children` method to continue to traverse down the tree. This mostly worked, but it messed with some of the spec when a single `code` block was nested in the `pre` block, so I added a line to handle that specific case.
I also noticed the `node_for` function in the `spec_helper` was using `Nokogiri::XML` instead of `Nokogiri::HTML`. It was messing with my tests so …
> Add treat_children to pre converter

- .travis.yml
- lib/reverse_markdown/converters/ignore.rb
- reverse_markdown.gemspec
- spec/html_to_markdown_to_html_spec.rb
- spec/spec_helper.rb
It seems the JRuby version of Nokogiri explicitly includes an empty head element when parsing a HTML fragment using `Nokogiri::HTML(fragment)`, whereas the MRI version does not. While it would be reasonable for Nokogiri to behave the same way on all platforms, it's not obvious whether that would be to remove head or to always include it, and given that the simple workaround to ignore head elements is sufficient to support both, it seems reasonable to not wait until Nokogiri is updated.
In order to avoid similar issues creeping up in the future, this adds a JRuby target to Travis, and patches the test suite to be compatible. In addition to handling the head element in `node_for`, it meant replacing redcarpet that requires a C-extension with pure Ruby kramdown instead.
While I suppose …
> Add support for JRuby

- lib/reverse_markdown/converters/bypass.rb
- spec/assets/tables.html
- spec/components/tables_spec.rb
This just adds a `register :tfoot, Bypass.new` so that `<tfoot>` is handled the say way as `<thead>`.
> Bypass `<tfoot>` tags to match how `<thead>` is handled.

- lib/reverse_markdown/converters/li.rb
- spec/html_to_markdown_to_html_spec.rb
It's possible to have lists that have a blank line between each list
item.
For example:
```
1. This is one line
2. This is the next line
```
This converts to the following html:
<ol>
<li><p>This is one line</p></li>
<li><p>This is the next line</p></li>
</ol>
This commit checks for the presence of the paragraph inside the list item.
> Deal with lists that have extra lines between them.

- lib/reverse_markdown.rb
This require is added in f21bd4973d57ec0b78f480d19aa8ad71cc6b24a7,
but it is no longer used since 24fca82fc4c65056f27b27af0b6cb2d05fe9f30b.
> Remove `require 'digest'` because it is no longer used

- Rakefile
- lib/reverse_markdown/config.rb
- reverse_markdown.gemspec
This pull request reduces warnings.
https://github.com/xijo/reverse_markdown/commit/1880de49fc5dc8e5500247b5ded2803566a9c886
It removes `s.rubyforge_project = "reverse_markdown"`. Because rubygems displays the following warning.
```
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/pocke/ghq/github.com/xijo/reverse_markdown/reverse_markdown.gemspec:14.
```
https://github.com/xijo/reverse_markdown/commit/af11e53e750e388ad8db76ae327a462cd788d187
`rake console` displays a `LoadError`, since Ruby 2.5.
```bash
$ bundle exec rake console
irb -rubygems -I lib -r reverse_markdown.rb
/home/pocke/.rbenv/versions/trunk/lib/ruby/2.7.0/irb/init.rb:290: warning: LoadError: …
```
> Reduce warnings

- .travis.yml
The language key is included in all the documentation examples.
> Travis: Drop commented-out section, add language

- .travis.yml
Unless there's a reason to test certain patch versions, this change will make Travis pick the latest available patch version. It will also reduce test times.
`cache: bundler` should also speed up future CI runs.
`script:` was removed, since the default task runs RSpec and `rake` is being [run by Travis](https://docs.travis-ci.com/user/languages/ruby/#default-build-script)
https://github.com/xijo/reverse_markdown/blob/e2c6973358d160214a79228b286cf55d57c1ae70/Rakefile#L8-L9
> Test only one patch version, add Ruby 2.7 to CI

- lib/reverse_markdown/converters/li.rb
- spec/assets/lists.html
- spec/components/lists_spec.rb
This commit aims to fix a problem when parsing markup similar to:
```ruby
[8] pry(main)> ReverseMarkdown.convert("<ul><li> <p>a</p></li></ul>")
=> "-  \n\na\n\n"
```
Note that the list item has newlines between the markdown list item and
the actual text.
If you remove the space between the list item tag and the paragraph tag:
```ruby
[7] pry(main)> ReverseMarkdown.convert("<ul><li><p>a</p></li></ul>")
=> "- a\n\n"
```
Reverse markdown appears to assume what believe to be the intended
behaviour. There was already a test in place to account for this situation,
but it was `xit`'ed.
The proposed patch is to ask Nokogiri to find the first child element of
the list, instead of the first child (which might include stuff like a
newline).
> Fixes unintentional newline characters within lists with paragraphs

- lib/reverse_markdown/converters/pre.rb
- spec/lib/reverse_markdown/converters/pre_spec.rb
It solves the issue I reported: #77
> Lets \n to be present in <pre> tag. solves #77

- lib/reverse_markdown/converters/ol.rb
- reverse_markdown.gemspec
- spec/assets/lists.html
- spec/components/lists_spec.rb
- spec/lib/reverse_markdown_spec.rb
- spec/spec_helper.rb
I have an issue when parsing text after a list.
```
<ul>
<li>item followed with a text</li>
</ul>
text after the list
```
This HTML is parsed as:
```
- item followed with a text
text after the list
```
But this markdown will collapse `text after the list` with `item followed with a text`.
We can check [here](https://spec.commonmark.org/dingus/?text=-%20liste%20avec%20un%20espace%0A%20hors-liste) the result.
With this changes, the new output is:
```
- item followed with a text
text after the list
```
And now, we don't have the text outside the list collapsed with the last list item.
We can check [here](https://spec.commonmark.org/dingus/?text=-%20item%20followed%20with%20a%20text%0A%0Atext%20after%20the%20list) again.
PS: I fixed a other test about UTF-8, I think that nokogiri changes the …
> Fix text sticking after list
